# coding=utf-8

# This is a basic map that transforms each player's Discord username into the
# name of their main character. If a player is not present in this list, then
# they either changed their Discord name, or they haven't been added to this list yet.
# I've added everyone to this list even if their Discord name matches their in-game name,
# this way if any name is processed that is not present in this list it can be raised as
# an immediate red flag.

DISCORD_NAME_MAPPING = {
    "Abstinence": "Abjection",
    "Akaran": "Akaran",
    "Albyno": "Albynonurse",
    "Ashori": "Ashori",
    "Baopi": "Baopi",
    "Brittany": "Brittany",
    "barnabae(hulk": "Barnabae",
    "barnabris(": "Barnabae",
    "barnabris(hul": "Barnabae",
    "barnabris(hulk)": "Barnabae",
    "ChubR0ck": "Lilchub",
    "chuunin": "Chuunin",
    "CrazyDaisy": "Crazydaisy",
    "Dalran": "Dalran",
    "Demeker": "Demeker",
    "Despia": "Despia",
    "Digie": "Digitalz",
    "Digie/Nekr": "Digitalz",
    "Digie/Nekryss": "Digitalz",
    "EllieVyra": "Ellievyra",
    "Envisage/Hyoli": "Hyolin",
    "Envisage/Hyol": "Hyolin",
    "Hyolin": "Hyolin",
    "Hyolin/Env": "Hyolin",
    "Hyolin/Envi": "Hyolin",
    "Hyolin/Envishi": "Hyolin",
    "Hulkhigginz": "Barnabae",
    "hulkhigginz": "Barnabae",
    "Jahmee": "Jaamii",
    "Justin": "Justinjr",
    "Kang": "Kangdude",
    "Kiele": "Kiele",
    "Kinasa": "Kinestra",
    "Kinastra": "Kinestra",
    "Kinestra": "Kinestra",
    "kharagan": "Kharagan",
    "Kortey": "Korteh",
    "Krumson": "Krumonx",
    "Malchazor": "Malchazor",
    "Metasyn": "Metasyn",
    "Murduc": "Murduc",
    "Nashy": "Nashborne",
    "NukeJr(Searious)": "Searious",
    "NukeJr(Seario": "Searious",
    "pikachau": "Pikachau",
    "Raya": "Rayashaman",
    "Reminosc": "Spookyremi",
    "rotheart": "Rotheart",
    "Salchant": "Salchant",
    "Searious": "Searious",
    "Seion": "Seion",
    "sekdar(sek": "Sekkondary",
    "sekdar(sekjr": "Sekkondary",
    "sekdar(sekjr)": "Sekkondary",
    "sekdar(sekkon": "Sekkondary",
    "sekdar(sekkondary)": "Sekkondary",
    "Shnacks": "Shnacks",
    "Simptease": "Wildshrimp",
    "Solljus/Verm": "Vermora",
    "Spookyremi-Re": "Spookyremi",    
    "Stephany": "Stephany",
    "Sylador": "Sylador",
    "Telyris": "Velyri",
    "Thaladred(Cra": "Crazydaisy",
    "Thorinix": "Thorinix",
    "Velyri": "Velyri",
    "Velyris": "Velyri",
    "Vermora": "Vermora",
    "Wildshrimp": "Wildshrimp",
    "Zerxx": "Zerxx",
}

def resolveName(discordName):
    return DISCORD_NAME_MAPPING[discordName]