20515:
  item-name: Abyssal Scepter
12363:
  item-name: Arcane Crystal
13036:
  item-name: Assassination Blade
12800:
  item-name: Azerothian Diamond
13126:
  item-name: Battlecaller Gauntlets
16864:
  item-name: Belt of Might
11382:
  item-name: Blood of the Mountain
19726:
  item-name: Bloodvine
12361:
  item-name: Blue Sapphire
16861:
  item-name: Bracers of Might
16828:
  item-name: Cenarion Belt
16830:
  item-name: Cenarion Bracers
17012:
  item-name: Core Leather
19162:
  item-name: Corehound Belt
1703:
  item-name: Crystal Basilisk Spine
15407:
  item-name: Cured Rugged Hide
11371:
  item-name: Dark Iron Bar
11370:
  item-name: Dark Iron Ore
20520:
  item-name: Dark Rune
13075:
  item-name: Direwing Legguards
13053:
  item-name: Doombringer
13133:
  item-name: Drakesfire Epaulets
13023:
  item-name: Eaglehorn Long Bow
9402:
  item-name: Earthborn Kilt
10215:
  item-name: Elegant Robes of Nature Resistance
15940:
  item-name: Elegant Scepter of Frozen Wrath
7067:
  item-name: Elemental Earth
7068:
  item-name: Elemental Fire
18562:
  item-name: Elementium Ore
12810:
  item-name: Enchanted Leather
7076:
  item-name: Essence of Earth
7078:
  item-name: Essence of Fire
14256:
  item-name: Felcloth
16806:
  item-name: Felheart Belt
16804:
  item-name: Felheart Bracers
18232:
  item-name: Field Repair Bot 74A
17010:
  item-name: Fiery Core
19272:
  item-name: Five of Elementals
19281:
  item-name: Five of Portals
16251:
  item-name: "Formula: Enchant Bracer - Superior Stamina"
11224:
  item-name: "Formula: Enchant Shield - Frost Resistance"
18356:
  item-name: "Garona: A Study on Stealth and Treachery"
16851:
  item-name: Giantstalker's Belt
16850:
  item-name: Giantstalker's Bracers
16817:
  item-name: Girdle of Prophecy
0:
  item-name: Gold
13926:
  item-name: Golden Pearl
12036:
  item-name: Granite Necklace of Nature Resistance
13457:
  item-name: Greater Fire Protection Potion
8846:
  item-name: Gromsblood
10142:
  item-name: High Councillor's Mantle of Frozen Wrath
10144:
  item-name: Hich Councillor's Sash of Healing
19183:
  item-name: Hourglass Sand
12364:
  item-name: Huge Emerald
16204:
  item-name: Illusion Dust
14227:
  item-name: Ironweb Spider Silk
1529:
  item-name: Jade
11978:
  item-name: Jasper Link of Nature Resistance
14344:
  item-name: Large Brilliant Shard
12799:
  item-name: Large Opal
18512:
  item-name: Larval Acid
16858:
  item-name: Lawbringer Belt
16857:
  item-name: Lawbringer Bracers
17011:
  item-name: Lava Core
13135:
  item-name: Lordly Armguards
13007:
  item-name: Mageflame Cloak
13107:
  item-name: Magiskull Cuffs
13001:
  item-name: Maiden's Circle
13006:
  item-name: Mass of McGowan
10255:
  item-name: Master's Belt of the Eagle
10247:
  item-name: Master's Boots of Frozen Wrath
10248:
  item-name: Master's Bracers of Frozen Wrath
10249:
  item-name: Master's Cloak of Frozen Wrath
10250:
  item-name: Master's Hat
10253:
  item-name: Master's Mantle of Frozen Wrath
10254:
  item-name: Master's Robe of Frozen Wrath
16825:
  item-name: Nightslayer Bracelets
15138:
  item-name: Onyxia Scale Cloak
14508:
  item-name: "Pattern: Felcloth Shoulders"
14501:
  item-name: "Pattern: Mooncloth Vest"
20548:
  item-name: "Pattern: Runed Stygian Belt"
20546:
  item-name: "Pattern: Runed Stygian Leggings"
11979:
  item-name: Peridot Circle of Nature Resistance
7976:
  item-name: "Plans: Mithril Shield Spike"
8028:
  item-name: "Plans: Runed Mithril Hammer"
12720:
  item-name: "Plans: Stronghold Gauntlets"
12703:
  item-name: "Plans: Storm Gauntlets"
12682:
  item-name: "Plans: Thorium Armor"
19767:
  item-name: Primal Bat Leather
19821:
  item-name: Punctured Voodoo Doll (Druid)
19816:
  item-name: Punctured Voodoo Doll (Hunter)
19818:
  item-name: Punctured Voodoo Doll (Mage)
19820:
  item-name: Punctured Voodoo Doll (Priest)
19819:
  item-name: Punctured Voodoo Doll (Warlock)
19699:
  item-name: Razzashi Coin
8170:
  item-name: Rugged Leather
11976:
  item-name: Sardonyx Knuckle of Nature Resistance
15410:
  item-name: Scale of Onyxia
5267:
  item-name: Scarlet Kris
10605:
  item-name: "Schematic: Spellpower Goggles Xtreme"
13015:
  item-name: Serathil
13144:
  item-name: Serenity Belt
11977:
  item-name: Serpentine Loop of Nature Resistance
13146:
  item-name: Shell Launcher Shotgun
14343:
  item-name: Small Brilliant Shard
13116:
  item-name: Spaulders of the Unseen
7910:
  item-name: Star Ruby
13072:
  item-name: Stonegrip Gauntlets
13423:
  item-name: Stonescale Oil
6622:
  item-name: Sword of Zeal
17203:
  item-name: Sulfuron Ingot
13060:
  item-name: The Needler
12359:
  item-name: Thorium Bar
13004:
  item-name: Torch of Austen
4500:
  item-name: Traveler's Backpack
13047:
  item-name: Twig of the World Tree
13130:
  item-name: Windrunner Legguards
13066:
  item-name: Wyrmslayer Spaulders
18677:
  item-name: Zephyr Cloak
