28774:
  content-tier: T4
  item-name: Glaive of the Pit
28775:
  content-tier: T4
  item-name: Thundering Greathelm
28776:
  content-tier: T4
  item-name: Liar's Tongue Gloves
28777:
  content-tier: T4
  item-name: Cloak of the Pit Stalker
28778:
  content-tier: T4
  item-name: Terror Pit Girdle
28779:
  content-tier: T4
  item-name: Girdle of the Endless Pit
28780:
  content-tier: T4
  item-name: Soul-Eater's Handwraps
28781:
  content-tier: T4
  item-name: Karaborian Talisman
28782:
  content-tier: T4
  item-name: Crystalheart Pulse-Staff
28783:
  content-tier: T4
  item-name: Eredar Wand of Obliteration
28789:
  content-tier: T4
  item-name: Eye of Magtheridon
28794:
  content-tier: T4
  item-name: Axe of the Gronn Lords
28795:
  content-tier: T4
  item-name: Bladespire Warbands
28796:
  content-tier: T4
  item-name: Malefic Mask of the Shadows
28797:
  content-tier: T4
  item-name: Brute Cloak of the Ogre-Magi
28799:
  content-tier: T4
  item-name: Belt of Divine Inspiration
28800:
  content-tier: T4
  item-name: Hammer of the Naaru
28801:
  content-tier: T4
  item-name: Maulgar's Warhelm
28802:
  content-tier: T4
  item-name: Bloodmaw Magus-Blade
28803:
  content-tier: T4
  item-name: Cowl of Nature's Breath
28804:
  content-tier: T4
  item-name: Collar of Cho'gall
28810:
  content-tier: T4
  item-name: Windshear Boots
28822:
  content-tier: T4
  item-name: Teeth of Gruul
28823:
  content-tier: T4
  item-name: Eye of Gruul
28824:
  content-tier: T4
  item-name: Gauntlets of Martial Perfection
28825:
  content-tier: T4
  item-name: Aldori Legacy Defender
28826:
  content-tier: T4
  item-name: Shuriken of Negation
28827:
  content-tier: T4
  item-name: Gauntlets of the Dragonslayer
28828:
  content-tier: T4
  item-name: Gronn-Stitched Girdle
28830:
  content-tier: T4
  item-name: Dragonspine Trophy
29458:
  content-tier: T4
  item-name: Aegis of the Vindicator
29753:
  content-tier: T4
  item-name: Chestguard of the Fallen Defender
29754:
  content-tier: T4
  item-name: Chestguard of the Fallen Champion
29755:
  content-tier: T4
  item-name: Chestguard of the Fallen Hero
29762:
  content-tier: T4
  item-name: Pauldrons of the Fallen Hero
29763:
  content-tier: T4
  item-name: Pauldrons of the Fallen Champion
29764:
  content-tier: T4
  item-name: Pauldrons of the Fallen Defender
29765:
  content-tier: T4
  item-name: Leggings of the Fallen Hero
29766:
  content-tier: T4
  item-name: Leggings of the Fallen Champion
29767:
  content-tier: T4
  item-name: Leggings of the Fallen Defender
32385:
  content-tier: T4
  item-name: Magtheridon's Head
34845:
  content-tier: T4
  item-name: Pit Lord's Satchel
29918:
  content-tier: T5
  item-name: Mindstorm Wristbands
29920:
  content-tier: T5
  item-name: Phoenix-Ring of Rebirth
29921:
  content-tier: T5
  item-name: Fire Crest Breastplate
29922:
  content-tier: T5
  item-name: Band of Al'ar
29923:
  content-tier: T5
  item-name: Talisman of the Sun King
29924:
  content-tier: T5
  item-name: Netherbane
29925:
  content-tier: T5
  item-name: Phoenix-Wing Cloak
29947:
  content-tier: T5
  item-name: Gloves of the Searing Grip
29948:
  content-tier: T5
  item-name: Claw of the Phoenix
29949:
  content-tier: T5
  item-name: Arcanite Steam-Pistol
29950:
  content-tier: T5
  item-name: Greaves of the Bloodwarder
29951:
  content-tier: T5
  item-name: Star-Strider Boots
29962:
  content-tier: T5
  item-name: Heartrazor
29965:
  content-tier: T5
  item-name: Girdle of the Righteous Path
29966:
  content-tier: T5
  item-name: Vambraces of Ending
29972:
  content-tier: T5
  item-name: Trousers of the Astromancer
29976:
  content-tier: T5
  item-name: Worldstorm Gauntlets
29977:
  content-tier: T5
  item-name: Star-Soul Breeches
29981:
  content-tier: T5
  item-name: Ethereum Life-Staff
29982:
  content-tier: T5
  item-name: Wand of the Forgotten Star
29983:
  content-tier: T5
  item-name: Fel-Steel Warhelm
29984:
  content-tier: T5
  item-name: Girdle of Zaetar
29985:
  content-tier: T5
  item-name: Void Reaver Greaves
29986:
  content-tier: T5
  item-name: Cowl of the Grand Engineer
29987:
  content-tier: T5
  item-name: Gauntlets of the Sun King
29988:
  content-tier: T5
  item-name: The Nexus Key
29989:
  content-tier: T5
  item-name: Sunshower Light Cloak
29990:
  content-tier: T5
  item-name: Crown of the Sun
29991:
  content-tier: T5
  item-name: Sunhawk Leggings
29992:
  content-tier: T5
  item-name: Royal Cloak of the Sunstriders
29993:
  content-tier: T5
  item-name: Twinblade of the Phoenix
29994:
  content-tier: T5
  item-name: Thalassian Wildercloak
29995:
  content-tier: T5
  item-name: Leggings of Murderous Intent
29996:
  content-tier: T5
  item-name: Rod of the Sun King
29997:
  content-tier: T5
  item-name: Band of the Ranger-General
29998:
  content-tier: T5
  item-name: Royal Gauntlets of Silvermoon
30008:
  content-tier: T5
  item-name: Pendant of the Lost Ages
30020:
  content-tier: T5
  item-name: Fire-Cord of the Magus
30021:
  content-tier: T5
  item-name: Wildfury Greatstaff
30022:
  content-tier: T5
  item-name: Pendant of the Perilous
30023:
  content-tier: T5
  item-name: Totem of the Maelstrom
30024:
  content-tier: T5
  item-name: Mantle of the Elven Kings
30025:
  content-tier: T5
  item-name: Serpentshrine Shuriken
30026:
  content-tier: T5
  item-name: Bands of the Celestial Archer
30027:
  content-tier: T5
  item-name: Boots of Courage Unending
30028:
  content-tier: T5
  item-name: Seventh Ring of the Tirisfalen
30029:
  content-tier: T5
  item-name: Bark-Gloves of Ancient Wisdom
30030:
  content-tier: T5
  item-name: Girdle of Fallen Stars
30047:
  content-tier: T5
  item-name: Blackfathom Warbands
30048:
  content-tier: T5
  item-name: Brighthelm of Justice
30049:
  content-tier: T5
  item-name: Fathomstone
30050:
  content-tier: T5
  item-name: Boots of the Shifting Nightmare
30051:
  content-tier: T5
  item-name: Idol of the Crescent Goddess
30052:
  content-tier: T5
  item-name: Ring of Lethality
30053:
  content-tier: T5
  item-name: Pauldrons of the Wardancer
30054:
  content-tier: T5
  item-name: Ranger-General's Chestguard
30055:
  content-tier: T5
  item-name: Shoulderpads of the Stranger
30056:
  content-tier: T5
  item-name: Robe of Hateful Echoes
30057:
  content-tier: T5
  item-name: Bracers of Eradication
30058:
  content-tier: T5
  item-name: Mallet of the Tides
30059:
  content-tier: T5
  item-name: Choker of Animalistic Fury
30060:
  content-tier: T5
  item-name: Boots of Effortless Striking
30061:
  content-tier: T5
  item-name: Ancestral Ring of Conquest
30062:
  content-tier: T5
  item-name: Grove-Bands of Remulos
30063:
  content-tier: T5
  item-name: Libram of Absolute Truth
30064:
  content-tier: T5
  item-name: Cord of Screaming Terrors
30065:
  content-tier: T5
  item-name: Glowing Breastplate of Truth
30066:
  content-tier: T5
  item-name: Tempest-Strider Boots
30067:
  content-tier: T5
  item-name: Velvet Boots of the Guardian
30068:
  content-tier: T5
  item-name: Girdle of the Tidal Call
30075:
  content-tier: T5
  item-name: Gnarled Chestpiece of the Ancients
30079:
  content-tier: T5
  item-name: Illidari Shoulderpads
30080:
  content-tier: T5
  item-name: Luminescent Rod of the Naaru
30081:
  content-tier: T5
  item-name: Warboots of Obliteration
30082:
  content-tier: T5
  item-name: Talon of Azshara
30083:
  content-tier: T5
  item-name: Ring of Sundered Souls
30084:
  content-tier: T5
  item-name: Pauldrons of the Argent Sentinel
30085:
  content-tier: T5
  item-name: Mantle of the Tireless Tracker
30090:
  content-tier: T5
  item-name: World Breaker
30091:
  content-tier: T5
  item-name: True-Aim Stalker Bands
30092:
  content-tier: T5
  item-name: Orca-Hide Boots
30095:
  content-tier: T5
  item-name: Fang of the Leviathan
30096:
  content-tier: T5
  item-name: Girdle of the Invulnerable
30097:
  content-tier: T5
  item-name: Coral-Barbed Shoulderpads
30098:
  content-tier: T5
  item-name: Razor-Scale Battlecloak
30099:
  content-tier: T5
  item-name: Frayed Tether of the Drowned
30100:
  content-tier: T5
  item-name: Soul-Strider Boots
30101:
  content-tier: T5
  item-name: Bloodsea Brigand's Vest
30102:
  content-tier: T5
  item-name: Krakken-Heart Breastplate
30103:
  content-tier: T5
  item-name: Fang of Vashj
30104:
  content-tier: T5
  item-name: Cobra-Lash Boots
30105:
  content-tier: T5
  item-name: Serpent Spine Longbow
30106:
  content-tier: T5
  item-name: Belt of One-Hundred Deaths
30107:
  content-tier: T5
  item-name: Vestments of the Sea-Witch
30108:
  content-tier: T5
  item-name: Lightfathom Scepter
30109:
  content-tier: T5
  item-name: Ring of Endless Coils
30110:
  content-tier: T5
  item-name: Coral Band of the Revived
30111:
  content-tier: T5
  item-name: Runetotem's Mantle
30112:
  content-tier: T5
  item-name: Glorious Gauntlets of Crestfall
30236:
  content-tier: T5
  item-name: Chestguard of the Vanquished Champion
30237:
  content-tier: T5
  item-name: Chestguard of the Vanquished Defender
30238:
  content-tier: T5
  item-name: Chestguard of the Vanquished Hero
30239:
  content-tier: T5
  item-name: Gloves of the Vanquished Champion
30240:
  content-tier: T5
  item-name: Gloves of the Vanquished Defender
30241:
  content-tier: T5
  item-name: Gloves of the Vanquished Hero
30242:
  content-tier: T5
  item-name: Helm of the Vanquished Champion
30243:
  content-tier: T5
  item-name: Helm of the Vanquished Defender
30244:
  content-tier: T5
  item-name: Helm of the Vanquished Hero
30245:
  content-tier: T5
  item-name: Leggings of the Vanquished Champion
30246:
  content-tier: T5
  item-name: Leggings of the Vanquished Defender
30247:
  content-tier: T5
  item-name: Leggings of the Vanquished Hero
30248:
  content-tier: T5
  item-name: Pauldrons of the Vanquished Champion
30249:
  content-tier: T5
  item-name: Pauldrons of the Vanquished Defender
30250:
  content-tier: T5
  item-name: Pauldrons of the Vanquished Hero
30282:
  content-tier: T5
  item-name: 'Pattern: Boots of Blasting'
30283:
  content-tier: T5
  item-name: 'Pattern: Boots of the Long Road'
30305:
  content-tier: T5
  item-name: 'Pattern: Boots of Natural Grace'
30306:
  content-tier: T5
  item-name: 'Pattern: Boots of Utter Darkness'
30307:
  content-tier: T5
  item-name: 'Pattern: Boots of the Crimson Hawk'
30308:
  content-tier: T5
  item-name: 'Pattern: Hurricane Boots'
30323:
  content-tier: T5
  item-name: 'Plans: Boots of the Protector'
30324:
  content-tier: T5
  item-name: 'Plans: Red Havoc Boots'
30446:
  content-tier: T5
  item-name: Solarian's Sapphire
30447:
  content-tier: T5
  item-name: Tome of Fiery Redemption
30448:
  content-tier: T5
  item-name: Talon of Al'ar
30449:
  content-tier: T5
  item-name: Void Star Talisman
30450:
  content-tier: T5
  item-name: Warp-Spring Coil
30619:
  content-tier: T5
  item-name: Fel Reaver's Piston
30620:
  content-tier: T5
  item-name: Spyglass of the Hidden Fleet
30621:
  content-tier: T5
  item-name: Prism of Inner Calm
30626:
  content-tier: T5
  item-name: Sextant of Unstable Currents
30627:
  content-tier: T5
  item-name: Tsunami Talisman
30629:
  content-tier: T5
  item-name: Scarab of Displacement
30663:
  content-tier: T5
  item-name: Fathom-Brooch of the Tidewalker
30664:
  content-tier: T5
  item-name: Living Root of the Wildheart
30665:
  content-tier: T5
  item-name: Earring of Soulful Meditation
30720:
  content-tier: T5
  item-name: Serpent-Coil Braid
32267:
  content-tier: T5
  item-name: Boots of the Resilient
32405:
  content-tier: T5
  item-name: Verdant Sphere
32515:
  content-tier: T5
  item-name: Wristguards of Determination
32516:
  content-tier: T5
  item-name: Wraps of Purification
32944:
  content-tier: T5
  item-name: Talon of the Phoenix
33054:
  content-tier: T5
  item-name: The Seal of Danzalar
33055:
  content-tier: T5
  item-name: Band of Vile Aggression
33058:
  content-tier: T5
  item-name: Band of the Vigilant
