28774:
  content-tier: T4
  item-name: Glaive of the Pit
28775:
  content-tier: T4
  item-name: Thundering Greathelm
28776:
  content-tier: T4
  item-name: Liar's Tong Gloves
28777:
  content-tier: T4
  item-name: Cloak of the Pit Stalker
28778:
  content-tier: T4
  item-name: Terror Pit Girdle
28779:
  content-tier: T4
  item-name: Girdle of the Endless Pit
28780:
  content-tier: T4
  item-name: Soul-Eater's Handwraps
28781:
  content-tier: T4
  item-name: Karaborian Talisman
28782:
  content-tier: T4
  item-name: Crystalheart Pulse-Staff
28783:
  content-tier: T4
  item-name: Eredar Wand of Obliteration
28789:
  content-tier: T4
  item-name: Eye of Magtheridon
28794:
  content-tier: T4
  item-name: Axe of the Gronn Lords
28795:
  content-tier: T4
  item-name: Bladespire Warbands
28796:
  content-tier: T4
  item-name: Malefic Mask of the Shadows
28797:
  content-tier: T4
  item-name: Brute Cloak of the Ogre-Magi
28799:
  content-tier: T4
  item-name: Belt of Divine Inspiration
28800:
  content-tier: T4
  item-name: Hammer of the Naaru
28801:
  content-tier: T4
  item-name: Maulgar's Warhelm
28802:
  content-tier: T4
  item-name: Bloodmaw Magus-Blade
28803:
  content-tier: T4
  item-name: Cowl of Nature's Breath
28804:
  content-tier: T4
  item-name: Collar of Cho'gall
28810:
  content-tier: T4
  item-name: Windshear Boots
28822:
  content-tier: T4
  item-name: Teeth of Gruul
28823:
  content-tier: T4
  item-name: Eye of Gruul
28824:
  content-tier: T4
  item-name: Gauntlets of Martial Perfection
28825:
  content-tier: T4
  item-name: Aldori Legacy Defender
28826:
  content-tier: T4
  item-name: Shuriken of Negation
28827:
  content-tier: T4
  item-name: Gauntlets of the Dragonslayer
28828:
  content-tier: T4
  item-name: Gronn-Stitched Girdle
28830:
  content-tier: T4
  item-name: Dragonspine Trophy
29458:
  content-tier: T4
  item-name: Aegis of the Vindicator
29753:
  content-tier: T4
  item-name: Chestguard of the Fallen Defender
29754:
  content-tier: T4
  item-name: Chestguard of the Fallen Champion
29755:
  content-tier: T4
  item-name: Chestguard of the Fallen Hero
29762:
  content-tier: T4
  item-name: Pauldrons of the Fallen Hero
29763:
  content-tier: T4
  item-name: Pauldrons of the Fallen Champion
29764:
  content-tier: T4
  item-name: Pauldrons of the Fallen Defender
29765:
  content-tier: T4
  item-name: Leggings of the Fallen Hero
29766:
  content-tier: T4
  item-name: Leggings of the Fallen Champion
29767:
  content-tier: T4
  item-name: Leggings of the Fallen Defender
32385:
  content-tier: T4
  item-name: Magtheridon's Head
